# Generated by Django 4.1 on 2022-09-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_order_paid_amount_order_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
    ]
