# Generated by Django 4.1 on 2022-09-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_product_size_sizes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizes',
            options={'verbose_name_plural': 'Sizes'},
        ),
        migrations.AddField(
            model_name='sizes',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
