# Generated by Django 4.1 on 2022-09-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_order_email_remove_order_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizes',
            name='orderItem',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
